---
plugin:
  author: puppetlabs
  id: metadata-json-lint
  display: metadata-json-lint
  version: 0.1.0
  upstream_project_url: https://github.com/voxpupuli/metadata-json-lint

gem:
  name: [metadata-json-lint]
  executable: metadata-json-lint

common:
  default_args: [ "/code/metadata.json" ]
  requires_git: true
  can_validate: true
  needs_write_access: false
  help_arg: '--help'
  success_exit_code: 0
  interleave_stdout_err: false